server:
  port: 9091

spring:
  application:
    name: BACKEND-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://registry-service:8761/eureka/"
  instance:
    hostname: localhost